# minimal-black theme + custom configuration

# Timeout
timeout 5

# Whether to store rEFInd's rEFInd-specific variables in NVRAM
# If you need to reset it, better use the one from OpenCore
use_nvram false

# Hide user interface elements
hideui label,singleuser,safemode,hwtest,arrows,hints,badges

# Set the name of a subdirectory in which icons are stored
icons_dir themes/minimal-black/icons

# Use a custom title banner instead of the rEFInd icon and name
banner themes/minimal-black/background.png

# Specify how to handle banners that aren't exactly the same as the screen size
banner_scale fillscreen

# Custom images for the selection background
selection_big themes/minimal-black/selection_big.png
selection_small themes/minimal-black/selection_small.png

# Launch specified OSes in graphics mode
use_graphics_for osx,windows,linux

# Non-bootloader tools to show on the tools line
showtools reboot,shutdown,shell

# Which types of boot loaders to search
scanfor internal,manual

# Directories that should NOT be scanned for boot loaders
dont_scan_dirs EFI/BOOT,EFI/cachyos,EFI/Microsoft/Boot,EFI/OC

# Files that should NOT be included as EFI boot loaders
dont_scan_files vmlinuz-linux-cachyos,vmlinuz-linux-cachyos-lts,bootmgfw.efi

# Set the default menu selection
default_selection Windows

# Manual configuration stanzas (boot entries)
# This is normally found automatically, but let's give each OS a custom name and order

# Windows
menuentry "Windows 11" {
    ostype "Windows"
    graphics "on"
    icon /EFI/refind/themes/minimal-black/icons/os_win.png
    volume "EFI"
    loader /EFI/Microsoft/Boot/bootmgfw.efi
}

# macOS
menuentry "macOS" {
    ostype "MacOS"
    graphics "on"
    icon /EFI/refind/themes/minimal-black/icons/os_mac.png
    volume "EFI"
    loader /EFI/OC/OpenCore.efi
}

# CachyOS
# "rootflags=subvol=@" is required for Btrfs
# "loglevel=3" shows error conditions
# "rw" mounts the filesystem in read-write
# "quiet" suppresses most kernel log messages during boot for a clean boot
# "splash" shows a boot splash screen
menuentry "CachyOS" {
    ostype "Linux"
    graphics "on"
    icon /EFI/refind/themes/minimal-black/icons/os_linux.png
    volume "CachyOS"
    loader /@/boot/vmlinuz-linux-cachyos
    initrd /@/boot/initramfs-linux-cachyos.img
    options "root=UUID=09354f10-a3e8-4ec6-a95c-2adbad1735ea rootflags=subvol=@ loglevel=3 rw quiet splash"
}
